name: Release

on:
  release:
    types: [published]

jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.2
      - uses: actions/checkout@v2.4.0
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build dist packages
        run: python setup.py sdist bdist_wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.1
      - uses: actions/setup-python@v2.3.2
      - uses: actions/checkout@v2.4.0
      - run: python set_version.py
      - name: Upload packages
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
